import * as THREE from './assets/vendor/three.module.js';
import {buildCity} from './login-city.js';
import {buildPeople} from './login-people.js';
import {trafficAt,carPositionsAt} from './login-traffic.js';
const host=document.querySelector('#scene'),depart=document.querySelector('#depart'),motion=document.querySelector('#motion'),status=document.querySelector('#scene-status');
try {
const scene=new THREE.Scene();scene.background=new THREE.Color('#55c9e5');scene.fog=new THREE.Fog('#c8e1e2',65,145);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;host.appendChild(renderer.domElement);
// Local studio-sky environment gives glass and paint real reflected highlights.
const envCanvas=document.createElement("canvas");envCanvas.width=512;envCanvas.height=256;const ec=envCanvas.getContext("2d"),gradient=ec.createLinearGradient(0,0,0,256);gradient.addColorStop(0,"#99cadb");gradient.addColorStop(.46,"#f8fbff");gradient.addColorStop(.53,"#bfd0ca");gradient.addColorStop(1,"#6d8284");ec.fillStyle=gradient;ec.fillRect(0,0,512,256);ec.fillStyle="#ffffff";ec.fillRect(75,45,100,45);ec.fillRect(350,70,45,65);const envTexture=new THREE.CanvasTexture(envCanvas);envTexture.mapping=THREE.EquirectangularReflectionMapping;envTexture.colorSpace=THREE.SRGBColorSpace;const pmrem=new THREE.PMREMGenerator(renderer),envTarget=pmrem.fromEquirectangular(envTexture);scene.environment=envTarget.texture;scene.environmentIntensity=.55;envTexture.dispose();pmrem.dispose();
const camera=new THREE.OrthographicCamera(-20,20,20,-20,.1,150),target=new THREE.Vector3(0,3.3,-1);const base=new THREE.Vector3(18,27,46);camera.position.copy(base);camera.lookAt(target);
scene.add(new THREE.HemisphereLight(0xffffff,0x83b6ba,1.25));const sun=new THREE.DirectionalLight(0xfff5df,2.5);sun.position.set(-12,30,20);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-35,right:35,top:35,bottom:-35});sun.shadow.normalBias=.025;sun.shadow.bias=-.00015;sun.shadow.radius=2;sun.shadow.camera.near=1;sun.shadow.camera.far=110;sun.shadow.camera.updateProjectionMatrix();scene.add(sun);
const {train,restX,bus,cars,updateLandmarks}=buildCity(scene);
const people=buildPeople(scene);
let trafficTime=0;
carPositionsAt(0).forEach((x,i)=>cars[i].position.x=x);
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),desired=new THREE.Vector2(),current=new THREE.Vector2();let travelling=false,elapsed=0,idle=0,last=performance.now(),paused=matchMedia('(prefers-reduced-motion: reduce)').matches;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
function sync(){motion.textContent=paused?'Resume motion':'Pause motion';motion.setAttribute('aria-pressed',String(paused));depart.disabled=travelling||paused;status.textContent=paused?'Motion paused':travelling?'Train departing…':'Traffic runs automatically · Move to explore'}
function start(){if(travelling||paused)return;travelling=true;elapsed=0;idle=0;sync()}
depart.disabled=false;depart.addEventListener('click',start);motion.onclick=()=>{paused=!paused;desired.set(0,0);sync()};reduced.addEventListener('change',e=>{paused=e.matches;sync()});
function hit(e){const r=host.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.intersectObject(train,true).length>0}
host.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'&&!paused){const r=host.getBoundingClientRect();desired.set(((e.clientX-r.left)/r.width-.5)*2,((e.clientY-r.top)/r.height-.5)*2)}renderer.domElement.style.cursor=hit(e)&&!travelling&&!paused?'pointer':'default'});host.addEventListener('pointerleave',()=>desired.set(0,0));host.addEventListener('click',e=>{if(hit(e))start()});
function resize(){const {width,height}=host.getBoundingClientRect();const aspect=width/height,half=Math.max(15.4,16.3/Math.max(aspect,.85));camera.left=-half*aspect;camera.right=half*aspect;camera.top=half;camera.bottom=-half;camera.updateProjectionMatrix();renderer.setSize(width,height,false)}new ResizeObserver(resize).observe(host);resize();sync();
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;if(document.hidden)return;if(!paused){trafficTime+=dt;people.update(trafficTime);updateLandmarks(trafficTime);const traffic=trafficAt(trafficTime);bus.position.x=traffic.busX;bus.visible=traffic.busVisible;carPositionsAt(trafficTime).forEach((x,i)=>cars[i].position.x=x);current.lerp(desired,1-Math.exp(-dt*4));camera.position.set(base.x+current.x*3.5,base.y+current.y*2,base.z-current.x*2.5);camera.lookAt(target);if(!travelling){idle+=dt;if(idle>=2)start()}if(travelling){elapsed+=dt;let x;if(elapsed<5){x=restX-elapsed*elapsed*1.8}else if(elapsed<6){x=restX-45}else if(elapsed<11){const t=(elapsed-6)/5;x=restX+52*(1-t)*(1-t)}else{x=restX;travelling=false;sync()}train.position.x=x;train.visible=elapsed<5||elapsed>=6}}renderer.render(scene,camera)}requestAnimationFrame(frame);
window.addEventListener('pagehide',()=>{envTarget.dispose();renderer.dispose()},{once:true});
} catch(error){console.error(error);document.querySelector('#scene-fallback').hidden=false;status.textContent='3D is unavailable on this device.';depart.disabled=true;motion.disabled=true}
